### ISSUE TITLE
Working globally but not with virtualenv

### ISSUE THREAD

**Issue by nunoh** [ssato/python-anyconfig#14]
I'm having some troubles getting `anyconfig` to work with `virtualenv`. 

I have a sample `testing.py` file with:

```
import anyconfig
a = anyconfig.load("foo.yml")
print a
````

If I use the global `anyconfig` module, I get the following:
```
No handlers could be found for logger "anyconfig.template"
{'something': {'foo': 'bar', 'bar': 'foo'}}
```

but with `virtualenv` I don't get anything:
```
No handlers could be found for logger "anyconfig.backend.yaml_"
None
```

Any idea what I might be missing here? Thanks!

**Comment by ssato** [comment]
I guess that it happens if anyconfig.backend.yaml_ was initialized and YAML is not available in
the environment virtualenv setup. This also may happen for other modules loaded from 
anyconfig.api (thru anyconfig.__init__) before the global logger was initialized
if my guess is true.

Anyway, I pushed possible fixes for this issue: a428698, d52634d and 4313b59.
Could you please try the HEAD version or wait for the next release 0.7 which
I'm planning to release this weekend ?

**Comment by ssato** [comment]
oops; s/0.7/0.0.7/

**Comment by nunoh** [comment]
I've just tried it and yeah it fixes the problem. Thanks!
